### ISSUE TITLE
Please remove Game Theme Music from the Store. It is completely broken, and the developer has yet to fix it, even after a year or so of complaints from MANY users.

### ISSUE THREAD

**Issue by MagmaSlime123** [SteamDeckHomebrew/decky-plugin-store#72]
It has been over a year or so since this issue started happening, and the developer has yet to fix it, even after MANY complaints from users, including myself.

Due to YT's dumbass-ness, most, if any, music cannot be selected in its settings, making the plugin utterly unusable. SoundCloud and other music sources are a thing, and it shouldn't be that hard to allow music to be used from them.

Please remove this plugin from the Decky Store if its no longer in development.

**Comment by TrainDoctor** [comment]
> It has been over a year or so since this issue started happening, and the developer has yet to fix it, even after MANY complaints from users, including myself.
> 
> Due to YT's dumbass-ness, most, if any, music cannot be selected in its settings, making the plugin utterly unusable. SoundCloud and other music sources are a thing, and it shouldn't be that hard to allow music to be used from them.
> 
> Please remove this plugin from the Decky Store if its no longer in development.

So,


A) This is not the correct repository for an issue like this...
B) Please provide evidence of the plugin breaking Decky Loader itself or harming the performance for you or other users.
C) We test all plugins for functionality and this issue has never been reported to us.
D) An update to this plugin to fix it for users of Decky v3 (now stable) was merged last week.

This plugin is very much clearly still in development as you can see from point "D".

Lastly it looks like the plugin developer absolutely attempted to address your complaints with this latest update with the patch notes stating: 
> Changed YouTube proxy from Piped to Invidious to fix searching and playing songs

And most importantly, don't use it then. Ignore it. You don't think it works or don't like it's functionality. Cool, good for you. It passed it's testing process. Next time involve yourself in the testing process and submit levelheaded and reasonable feedback and hopefully whatever issues you believe are still experiencing will be resolved.

I'm closing this issue as wontfix and locking it primarily because the repository it was filed in is incorrect and secondarily because I'm insulted on behalf of the plugin developer at your shitty attitude. These plugins are freely distributed to you through our volunteer work and the vast majority of plugin developers request no compensation.
